### ISSUE TITLE
[bug] Memory leak when the service is in idle mode

### ISSUE THREAD

**Issue by frzifus** [led0nk/ark-overseer#19]
It seems that the memory utilisation is slowly increasing even when the service is not in use. I set a limit of 128Mi and the container was killed after about 2 weeks.

![grafik](https://github.com/user-attachments/assets/f4714a49-dc0f-42a3-bc58-392e1cd47087)

Here are the logs after the last restart.
```json
{"time":"2025-01-02T13:48:31.964574735Z","level":"INFO","msg":"server address","addr":"0.0.0.0:8080"}
{"time":"2025-01-02T13:48:31.96475324Z","level":"INFO","msg":"grpc address","grpcaddr":"backend.observability:4317"}
{"time":"2025-01-02T13:48:31.964768179Z","level":"INFO","msg":"level for logging","loglevel":"INFO"}
{"time":"2025-01-02T13:48:31.964778451Z","level":"INFO","msg":"path to database","db":"/data"}
{"time":"2025-01-02T13:48:31.964787487Z","level":"INFO","msg":"path to config","config":"/data"}
{"time":"2025-01-02T13:48:31.964796862Z","level":"INFO","msg":"path to blacklist","blacklist":"/data"}
{"time":"2025-01-02T13:48:31.976214319Z","level":"INFO","msg":"service subscribed to eventManager","event":{"service id":"410be7b1-c910-11ef-aab7-ea2175cc806f","service name":"observer"}}
{"time":"2025-01-02T13:48:31.976438469Z","level":"INFO","msg":"service subscribed to eventManager","event":{"service id":"410c5f5f-c910-11ef-aab7-ea2175cc806f","service name":"serviceManager"}}
{"time":"2025-01-02T13:48:31.976710695Z","level":"ERROR","msg":"failed to get section from config","serviceManager":{"error":"section notification-service not a valid type"}}
{"time":"2025-01-02T13:48:31.985015471Z","level":"INFO","msg":"listen and serve","http":{"addr":"0.0.0.0:8080"}}
```
These are the currently used resources.
```
$ kubectl top pod -n ark-overseer
NAME                           CPU(cores)   MEMORY(bytes)   
ark-overseer-6dbdf445b-w7wd4   250m         30Mi
```
And the used k8s deployment.
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ark-overseer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-database
  namespace: ark-overseer
spec:
  storageClassName: simple-and-fast-block
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-overseer
  namespace: ark-overseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ark-overseer
  template:
    metadata:
      labels:
        app: ark-overseer
    spec:
      containers:
      - name: ark-overseer
        image: ghcr.io/led0nk/ark-overseer:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        args:
        - "/ark-overseer"
        - "-addr=0.0.0.0:8080"
        - "-grpc=backend.observability:4317"
        - "-domain=ark-overseer.monkey-capella.ts.net"
        - "-blacklist=/data"
        - "-db=/data"
        - "-config=/data"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /data
          name: database
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        ports:
        - containerPort: 4180
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: cookie-secret
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: client-secret
        volumeMounts:
        - mountPath: /data
          name: database
        args:
        - "--provider=github"
        - "--github-org=xxx"
        - "--email-domain=*"
        - "--upstream=http://localhost:8080"
        - "--http-address=0.0.0.0:4180"
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: ark-database
---
apiVersion: v1
kind: Service
metadata:
  name: ark-overseer
  namespace: ark-overseer
spec:
  selector:
    app: ark-overseer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4180
```
Any idea whats wrong?
